### ISSUE TITLE
Resampling using standard deviation

### ISSUE THREAD

**Issue by BenjaminBorn** [femtotrader/TimeSeriesResampler.jl#14]
Thanks for this very useful package.

I'd like to compute the monthly standard deviation of daily returns. Would it be as simple as adding
```
function std(grp::GroupBy)
    std(grp.action)
end

function std(resampler::TimeArrayResampler)
    f_group = dt_grouper(resampler.tf, eltype(resampler.ta.timestamp))
    collapse(resampler.ta, f_group, dt -> f_group(first(dt)), std)
end
```
in resample.jl?

**Comment by femtotrader** [comment]
Hello Benjamin,

I suggest you to have a test driven development approach.

First define a test timeseries with daily returns
- a fake timeseries using something similar to https://github.com/femtotrader/TimeSeriesResampler.jl/blob/master/test/resample.jl#L20
- or using inline data (like https://github.com/JuliaStats/TimeSeries.jl/issues/297#issuecomment-259920767 with `IOBuffer` and `readtimearray`) in your test file
- or using a separate CSV file and `readtimearray`

Then, create your new API call in a test file

     std(resample(ta["Returns"], Dates.Month(1)))

Running your test should fail

Add to existing code your functions

Running your test shouldn't fail

Improve your test by testing if calculated values are equals to expected values

Running your test shouldn't fail again

Kind regards

**Comment by BenjaminBorn** [comment]
Thanks for your quick reply. I have followed your advice and everything works locally. I have prepared a pull request, if you're interested in the functionality, here: #15
